package br.com.fiap.chatbotdatabase1.enums;

public enum Tema {
    CHECAR_HOSPITAIS_PROXIMOS,
    AGENDAR_CONSULTA_OU_EXAME,
    REMARCAR_OU_CANCELAR_AGENDAMENTO,
    CONSULTAR_ESPECIALIDADES_MEDICAS_DISPONIVEIS,
    GERAR_2A_VIA_DO_BOLETO,
    VER_VENCIMENTO_DA_FATURA_ATUAL,
    CONSULTAR_HISTORICO_DE_PAGAMENTOS,
    ALTERAR_FORMA_DE_PAGAMENTO_DEBITO_BOLETO_CARTAO,
    BAIXAR_CARTEIRINHA_DIGITAL,
    RECUPERAR_SENHA_DO_APP,
    ATUALIZAR_DADOS_CADASTRAIS,
    AJUDA_COM_LOGIN_OU_ACESSO_NEGADO,
    ENVIAR_NOVA_SOLICITACAO_MEDICA,
    PRAZO_MEDIO_DE_APROVACAO,
    PROCEDIMENTO_NEGADO_O_QUE_FAZER,
    FALAR_COM_UM_ATENDENTE_HUMANO,
    REGISTRAR_RECLAMACAO_OU_SUGESTAO,
    HORARIO_DE_FUNCIONAMENTO_E_CANAIS_DE_CONTATO,
    VISUALIZAR_PLANOS_E_COBERTURA,
    INCLUSAO_DE_DEPENDENTES,
    PLANOS_EMPRESARIAIS_E_CORPORATIVOS
}