/*MySQL*/
/*Querys Relevantes*/
Select * From MENSAGEM;

Select * From RESPOSTA;

Select m.CONTEUDO, r.CONTEUDO, r.TEMA_PRINCIPAL, r.SATISFATORIO
From MENSAGEM m Inner Join RESPOSTA r
On m.ID_MENSAGEM = r.ID_MENSAGEM
Order By r.TEMA_PRINCIPAL
;

Select m.CONTEUDO, r.CONTEUDO, r.TEMA_PRINCIPAL, r.SATISFATORIO
From MENSAGEM m Inner Join RESPOSTA r
On m.ID_MENSAGEM = r.ID_MENSAGEM
Where r.SATISFATORIO = 1
Order By r.TEMA_PRINCIPAL
;

Select m.CONTEUDO, r.CONTEUDO, r.TEMA_PRINCIPAL, r.SATISFATORIO
From MENSAGEM m Inner Join RESPOSTA r
On m.ID_MENSAGEM = r.ID_MENSAGEM
Where r.TEMA_PRINCIPAL = "Checar Hospitais próximos"
Order By r.TEMA_PRINCIPAL
;